api: https://122e4e-mapbox.global.ssl.fastly.net
url: https://122e4e-mapbox.global.ssl.fastly.net
exclude:
  - README.markdown
  - nounproject
baseurl: /maki
permalink: /:title.html
markdown: rdiscount
